### ISSUE TITLE
KSPROPERTY_TYPE_SET return value is set to succeed

### ISSUE THREAD

**Issue by justanotheranonymoususer** [flowerinthenight/windows-camera-class-filter-driver#2]
I'm talking about [this line](https://github.com/flowerinthenight/windows-camera-class-filter-driver/blob/7bbce83b88c65b0ebf3f81574d6d12dfd19c1076/ccfltr/ccfltr.c#L629). Why is it there? If I try to use a camera with more than one app at the same time, `KSSTATE_ACQUIRE` fails for the second app (as expected), but because of that line the app thinks that it succeeded and it gets confused.

**Comment by flowerinthenight** [comment]
It's one of those parts that are not really tested very well. It would be appreciated if you can submit a PR for a fix?

**Comment by justanotheranonymoususer** [comment]
Here you go:
https://github.com/flowerinthenight/windows-camera-class-filter-driver/pull/3

I just removed that line.

**Comment by flowerinthenight** [comment]
Thanks very much. I just merged your PRs.

**Comment by justanotheranonymoususer** [comment]
Thanks!
