### ISSUE TITLE
Compile and installed, but not attached on usb camera

### ISSUE THREAD

**Issue by idreamerhx** [flowerinthenight/windows-camera-class-filter-driver#7]
Hi, 

I compiled this project in vs2017 and installed in latest windows10 in vmware. A usb camera is connected to the vm. After successfully installed, It seem nothing changed in Device Manager / Camera / USB Camera / Driver Details.

In my opinion this driver is a filter which works after ksthunk.sys

And, I can't see log output in dbgview

**Comment by flowerinthenight** [comment]
I don't have an available Windows box anymore so I can't confirm but based on https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors, it looks like Windows 10 changed the class GUID for camera devices. This filter was tested to attach to the old GUID:
https://github.com/flowerinthenight/windows-camera-class-filter-driver/blob/e770de47d7d7ec439a7b7b8780f28f7e4cf79d88/ccfltr/ccfltr.inf#L8

And yes you're right. This driver sits between ksthunk and the camera driver.

**Comment by idreamerhx** [comment]
Thanks. I change inf Class = Camera and ClassGuid = {ca3e7ab9-b4c3-4ae6-8251-579ef933890f}, the sys file loaded into Device Manager.

**Comment by BakingBrains** [comment]
@idreamerhx I changed the class and classguid, the filter is registered, but not at all showing.
Any suggestions?

Thank you.
